### PR TITLE
Added few missing packs

### PR DESCRIPTION
**Pull request by pyllyukko**

### CODE REVIEW

**Comment by tracker1** [comment]
@fcambus @pyllyukko   Been too long for this, but maybe change the file name to `acdu0996-fake.zip` and modify/prefix the .diz file?

**Comment by pyllyukko** [comment]
> modify/prefix the .diz file?

Like how?

**Comment by tracker1** [comment]
@pyllyukko extract the file_id.diz file, and prefix some info regarding it being a "fake" release.  :-)

**Comment by pyllyukko** [comment]
My question was more in the lines of "prefix with what?", and not about extracting/editing.

**Comment by pyllyukko** [comment]
Well I guess it's still there in the Git history, so it might not matter that much. Note added.

**Comment by tracker1** [comment]
@lordscarlet @fcambus @ispyhumanfly

**Review by lordscarlet — APPROVED** [review]

**Pull request merged**
