### PR TITLE
33RULES now v2

### PR DESCRIPTION
**Pull request by qu33**
hello!  in the time since i uploaded 33RULES.ZIP i found a bunch of files that should have been included but were not, & also i dug some previously unreleased ansi from my old backups — & so this is v2 of that pack.  it also comes with an intro file, a complete list of packs/groups & an easter egg.  it's better i guess?  could you all be so kind as to replace the old one with this (now called 33RULES2.ZIP)?  thanks!  & peace to the 2016 ansi scene, sorry i can't do more, i just want to close this little box of souvenirs.  bye,  ~33

### CODE REVIEW

**Comment by lordscarlet** [comment]
Not the best place to have a conversation, but any chance you're on Facebook? There is a group on there with artists that would love you say "hello" to you.

**Comment by gangster** [comment]
@qu33 was hoping you'd poke your head out.   -ky

**Comment by bricas** [comment]
@qu33 I'm going to close this pull request because you've added a new file instead of just updating the old one. No worries though, I've updated the file myself (commit 9d41265bcdbe3a50f973c1079bc6580fcc9d1b73).

Thanks for the update!

**Comment by qu33** [comment]
hi, i'm not on facebook because time + privacy.  but thanks for the good words.  hope you enjoy the pack.  take care,

**Comment by qu33** [comment]
@bricas it looks like the pack is not completely updated?  i see the new files have been added but it looks like some changes were not made.  for example i had fixed PICS/33-PIN.ANS which had a bug in it that made it look awkward.  some files were moved around which i don't see, & also there was a new FILE_ID.DIZ with mention of "version 2".  is it possible to "re-compile" (or however you do it) the pack with the full up-to-date contents?  thanks!  & sorry for being a bit picky!  ~33

**Comment by bricas** [comment]
@qu33 I think we've got it now. Sorry 'bout that.

**Comment by qu33** [comment]
@bricas thanks! that looks good.

**Pull request closed without merging**
